spring:
  application:
    name: rule-service
  cache:
    jcache:
      config: classpath:ehcache.xml


security:
  oauth2:
    resource:
      userInfoUri: https://srvbigpvlbr07.bs.br.bsch:8243/userinfo?schema=openid

br:
  produban:
    gemfire:
      persistent: false
      endpoint:
        CepRule: http://srvbigpvlbr10.bs.br.bsch:8282/gemfire-api/v1/CepRule
    camel:
      endpoint:
        metricsByTool: http://srvbigpvlbr07.bs.br.bsch:3030/api/tools/{tool}/metrics
    wso2:
      user: operador@produban.com.br
      pass: operador
      endpoint: 
        EventStreamAdminServiceSoap: https://srvbigpvlbr12.bs.br.bsch:9443/services/EventStreamAdminService.EventStreamAdminServiceHttpsSoap11Endpoint
        EventProcessorAdminServiceSoap: https://srvbigpvlbr12.bs.br.bsch:9443/services/EventProcessorAdminService.EventProcessorAdminServiceHttpsSoap11Endpoint
        
        


